spring:
  jpa:
    database: mysql
  #    database: h2
  #  datasource:
  #      driver-class-name: org.h2.Driver
  #      username: root
  #      password: root
  #      url: jdbc:h2:~/recruit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/recruit?serverTimezone=UTC
  #    data: classpath:data-mysql.sql
  #    initialization-mode: always
  h2:
    console:
      enabled: true
recruitFile:
  url: F:/file/employ