server:
  port: 8000
spring:
  data:
    jpa:
      repositories:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy/MM/dd
  main:
    banner-mode: off
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true